import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Nextjs fullstack</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-red-300">
        <h1 className=''> helo </h1>
      </main>
    </>
  )
}
